
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug 18 2026 09:55:37 KST (Aug 18 2026 00:55:37 UTC)

// Verification Directory fv/_4_BIT_SHIFT_REGISTER 

module _4_BIT_SHIFT_REGISTER(clr_n, clk, i_s, i_d, i_sr, i_sl, o_q);
  input clr_n, clk, i_sr, i_sl;
  input [1:0] i_s;
  input [3:0] i_d;
  output [3:0] o_q;
  wire clr_n, clk, i_sr, i_sl;
  wire [1:0] i_s;
  wire [3:0] i_d;
  wire [3:0] o_q;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  DFFRHQX1 \o_q_reg[0] (.RN (clr_n), .CK (clk), .D (n_15), .Q (o_q[0]));
  DFFRHQX1 \o_q_reg[1] (.RN (clr_n), .CK (clk), .D (n_18), .Q (o_q[1]));
  DFFRHQX1 \o_q_reg[3] (.RN (clr_n), .CK (clk), .D (n_16), .Q (o_q[3]));
  DFFRHQX1 \o_q_reg[2] (.RN (clr_n), .CK (clk), .D (n_19), .Q (o_q[2]));
  OAI211X1 g462__2398(.A0 (n_3), .A1 (n_17), .B0 (n_6), .C0 (n_13), .Y
       (n_19));
  OAI211X1 g465__5107(.A0 (n_1), .A1 (n_17), .B0 (n_7), .C0 (n_14), .Y
       (n_18));
  OAI211X1 g463__6260(.A0 (n_0), .A1 (n_17), .B0 (n_4), .C0 (n_9), .Y
       (n_16));
  OAI211X1 g464__4319(.A0 (n_2), .A1 (n_17), .B0 (n_5), .C0 (n_11), .Y
       (n_15));
  AOI22X1 g466__8428(.A0 (n_12), .A1 (o_q[1]), .B0 (n_10), .B1
       (o_q[2]), .Y (n_14));
  AOI22X1 g467__5526(.A0 (n_12), .A1 (o_q[2]), .B0 (n_8), .B1 (o_q[1]),
       .Y (n_13));
  AOI22X1 g468__6783(.A0 (n_12), .A1 (o_q[0]), .B0 (n_10), .B1
       (o_q[1]), .Y (n_11));
  AOI22X1 g469__3680(.A0 (n_8), .A1 (o_q[2]), .B0 (i_sr), .B1 (n_10),
       .Y (n_9));
  NAND2X1 g470__1617(.A (n_8), .B (o_q[0]), .Y (n_7));
  NAND2X1 g471__2802(.A (n_10), .B (o_q[3]), .Y (n_6));
  NAND2X1 g472__1705(.A (i_sl), .B (n_8), .Y (n_5));
  NAND2X1 g473__5122(.A (n_12), .B (o_q[3]), .Y (n_4));
  NAND2X1 g474__8246(.A (state[0]), .B (state[1]), .Y (n_17));
  NOR2BX1 g475__7098(.AN (state[1]), .B (state[0]), .Y (n_8));
  NOR2BX1 g476__6131(.AN (state[0]), .B (state[1]), .Y (n_10));
  NOR2X1 g477__1881(.A (state[0]), .B (state[1]), .Y (n_12));
  DFFRHQX1 \state_reg[1] (.RN (clr_n), .CK (clk), .D (i_s[1]), .Q
       (state[1]));
  DFFRHQX1 \state_reg[0] (.RN (clr_n), .CK (clk), .D (i_s[0]), .Q
       (state[0]));
  INVXL g480(.A (i_d[2]), .Y (n_3));
  INVXL g481(.A (i_d[0]), .Y (n_2));
  INVXL g482(.A (i_d[1]), .Y (n_1));
  INVXL g483(.A (i_d[3]), .Y (n_0));
endmodule

